//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cancer_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class casacomercial
    {
        public casacomercial()
        {
            this.droga = new HashSet<droga>();
        }
    
        public int idCasaComercial { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<droga> droga { get; set; }
    }
}
