//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cancer_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class citometria
    {
        public citometria()
        {
            this.semideen = new HashSet<semideen>();
        }
    
        public System.DateTime fechaRealizado { get; set; }
        public int idMuestra { get; set; }
        public int paciente { get; set; }
        public Nullable<bool> validado { get; set; }
        public string observaciones { get; set; }
        public byte[] pdfCitometro { get; set; }
    
        public virtual muestra muestra { get; set; }
        public virtual ICollection<semideen> semideen { get; set; }
    }
}
