//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cancer_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class componenteregla
    {
        public componenteregla()
        {
            this.ensayoinvitro = new HashSet<ensayoinvitro>();
        }
    
        public int idComponenteRegla { get; set; }
        public Nullable<int> valor { get; set; }
        public Nullable<int> relacion { get; set; }
        public int Indice_id { get; set; }
    
        public virtual indice indice { get; set; }
        public virtual ICollection<ensayoinvitro> ensayoinvitro { get; set; }
    }
}
