//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cancer_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class conjuntoexamenes
    {
        public conjuntoexamenes()
        {
            this.consistede = new HashSet<consistede>();
        }
    
        public System.DateTime fechaEnviados { get; set; }
        public int Paciente_numeroCedula { get; set; }
        public int Medico_idMedico { get; set; }
    
        public virtual medico medico { get; set; }
        public virtual paciente paciente { get; set; }
        public virtual ICollection<consistede> consistede { get; set; }
    }
}
