//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cancer_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class consistede
    {
        public string nombreExamen { get; set; }
        public System.DateTime fechaEnviadosExamenes { get; set; }
        public int paciente { get; set; }
        public int medico { get; set; }
        public Nullable<System.DateTime> fechaExamen { get; set; }
        public string resultado { get; set; }
        public string pronostico { get; set; }
        public string diagnostico { get; set; }
    
        public virtual conjuntoexamenes conjuntoexamenes { get; set; }
        public virtual examen examen { get; set; }
    }
}
