//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cancer_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class droga
    {
        public droga()
        {
            this.secomponede = new HashSet<secomponede>();
            this.tiene = new HashSet<tiene>();
        }
    
        public int idDroga { get; set; }
        public int idCasaComercial { get; set; }
        public string nombre { get; set; }
        public string storageAndStability { get; set; }
        public Nullable<float> C100_TDC { get; set; }
        public Nullable<float> stockSolution { get; set; }
    
        public virtual casacomercial casacomercial { get; set; }
        public virtual ICollection<secomponede> secomponede { get; set; }
        public virtual ICollection<tiene> tiene { get; set; }
    }
}
