//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cancer_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class ensayoinvitro
    {
        public ensayoinvitro()
        {
            this.estacompuestade = new HashSet<estacompuestade>();
        }
    
        public System.DateTime fechaHoraEnsayo { get; set; }
        public int idMuestra { get; set; }
        public int paciente { get; set; }
        public Nullable<int> tratamientoMasEfectivo { get; set; }
        public Nullable<int> tratamientoMenosEfectivo { get; set; }
        public Nullable<System.DateTime> fechaEnvioResultadoOncologo { get; set; }
        public Nullable<int> diasDuracionEnsayo { get; set; }
        public string realizadoPor { get; set; }
        public Nullable<bool> validado { get; set; }
        public Nullable<int> celulasPorPozo { get; set; }
        public Nullable<int> loteKit { get; set; }
        public byte[] datosCrudos { get; set; }
        public string recomendaciones { get; set; }
        public Nullable<bool> congelaronExtractos { get; set; }
        public byte[] resultado { get; set; }
        public int ComponenteRegla_idComponenteRegla { get; set; }
    
        public virtual componenteregla componenteregla { get; set; }
        public virtual muestra muestra { get; set; }
        public virtual tratamientoenmuestra tratamientoenmuestra { get; set; }
        public virtual tratamientoenmuestra tratamientoenmuestra1 { get; set; }
        public virtual ICollection<estacompuestade> estacompuestade { get; set; }
    }
}
