//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cancer_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class estacompuestade
    {
        public int paciente { get; set; }
        public int idMuestra { get; set; }
        public System.DateTime fechaHoraEnsayo { get; set; }
        public int idTratamiento { get; set; }
        public int indice { get; set; }
        public Nullable<int> numeroPlaca { get; set; }
        public Nullable<int> ordenEnPlaca { get; set; }
        public Nullable<float> valor { get; set; }
    
        public virtual ensayoinvitro ensayoinvitro { get; set; }
        public virtual tratamientoenmuestra tratamientoenmuestra { get; set; }
        public virtual indice indice1 { get; set; }
    }
}
