//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cancer_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class examen
    {
        public examen()
        {
            this.consistede = new HashSet<consistede>();
        }
    
        public string nombre { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<consistede> consistede { get; set; }
    }
}
