//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cancer_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class indice
    {
        public indice()
        {
            this.componenteregla = new HashSet<componenteregla>();
            this.estacompuestade = new HashSet<estacompuestade>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<componenteregla> componenteregla { get; set; }
        public virtual ICollection<estacompuestade> estacompuestade { get; set; }
    }
}
