//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cancer_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class localizacion
    {
        public localizacion()
        {
            this.muestra = new HashSet<muestra>();
        }
    
        public int idLocalizacion { get; set; }
        public string localizacion1 { get; set; }
    
        public virtual ICollection<muestra> muestra { get; set; }
    }
}
