//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cancer_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int Paciente_numeroCedula { get; set; }
        public string Usuario_nombreUsuario { get; set; }
        public System.DateTime fechaHora { get; set; }
        public int tipoAccion { get; set; }
        public int idTablaAfectada { get; set; }
    
        public virtual paciente paciente { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
