//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cancer_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class marcadores
    {
        public marcadores()
        {
            this.semideen = new HashSet<semideen>();
            this.seobtienen = new HashSet<seobtienen>();
        }
    
        public string nombre { get; set; }
    
        public virtual ICollection<semideen> semideen { get; set; }
        public virtual ICollection<seobtienen> seobtienen { get; set; }
    }
}
