//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cancer_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class medico
    {
        public medico()
        {
            this.conjuntoexamenes = new HashSet<conjuntoexamenes>();
            this.seguimiento = new HashSet<seguimiento>();
            this.terapiapersonalizada = new HashSet<terapiapersonalizada>();
        }
    
        public int idMedico { get; set; }
        public string nombre { get; set; }
        public string hospital { get; set; }
        public Nullable<int> servicio { get; set; }
    
        public virtual ICollection<conjuntoexamenes> conjuntoexamenes { get; set; }
        public virtual ICollection<seguimiento> seguimiento { get; set; }
        public virtual ICollection<terapiapersonalizada> terapiapersonalizada { get; set; }
    }
}
