//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cancer_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class muestra
    {
        public muestra()
        {
            this.citometria = new HashSet<citometria>();
            this.ensayoinvitro = new HashSet<ensayoinvitro>();
            this.patologia = new HashSet<patologia>();
        }
    
        public int idMuestra { get; set; }
        public int paciente { get; set; }
        public int idTipoTumor { get; set; }
        public int idLocalizacion { get; set; }
        public System.DateTime fechaHoraProcesada { get; set; }
        public string consistencia { get; set; }
        public Nullable<bool> pruebaEsterilidad { get; set; }
        public string encargadoDeProcesar { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> temperaturaAdecuada { get; set; }
        public Nullable<bool> separacionFicoll { get; set; }
        public Nullable<bool> refrigeradoAntesDelAnalisis { get; set; }
        public Nullable<System.DateTime> fechaHoraLlegadaPatologia { get; set; }
        public Nullable<double> peso { get; set; }
        public Nullable<int> conteoCelulasVivas { get; set; }
        public Nullable<double> volumen { get; set; }
        public Nullable<double> porcentajeViabilidad { get; set; }
        public Nullable<bool> contaminacionEritrocitos { get; set; }
        public Nullable<bool> apropiada { get; set; }
    
        public virtual ICollection<citometria> citometria { get; set; }
        public virtual ICollection<ensayoinvitro> ensayoinvitro { get; set; }
        public virtual localizacion localizacion { get; set; }
        public virtual paciente paciente1 { get; set; }
        public virtual tipotumor tipotumor { get; set; }
        public virtual ICollection<patologia> patologia { get; set; }
    }
}
