//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cancer_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class paciente
    {
        public paciente()
        {
            this.conjuntoexamenes = new HashSet<conjuntoexamenes>();
            this.log = new HashSet<log>();
            this.muestra = new HashSet<muestra>();
            this.seguimiento = new HashSet<seguimiento>();
            this.terapiapersonalizada = new HashSet<terapiapersonalizada>();
        }
    
        public int numeroCedula { get; set; }
        public string nombre { get; set; }
        public bool genero { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string observaciones { get; set; }
    
        public virtual ICollection<conjuntoexamenes> conjuntoexamenes { get; set; }
        public virtual ICollection<log> log { get; set; }
        public virtual ICollection<muestra> muestra { get; set; }
        public virtual ICollection<seguimiento> seguimiento { get; set; }
        public virtual ICollection<terapiapersonalizada> terapiapersonalizada { get; set; }
    }
}
