//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cancer_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class terapiapersonalizada
    {
        public terapiapersonalizada()
        {
            this.secomponede = new HashSet<secomponede>();
        }
    
        public int Paciente_numeroCedula { get; set; }
        public int Medico_idMedico { get; set; }
        public System.DateTime fechaRealizada { get; set; }
        public string nombre { get; set; }
    
        public virtual medico medico { get; set; }
        public virtual paciente paciente { get; set; }
        public virtual ICollection<secomponede> secomponede { get; set; }
    }
}
