//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cancer_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiene
    {
        public int tratamiento { get; set; }
        public int droga { get; set; }
        public Nullable<float> dosis { get; set; }
        public string lote_Droga { get; set; }
    
        public virtual droga droga1 { get; set; }
        public virtual tratamientoenmuestra tratamientoenmuestra { get; set; }
    }
}
