//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cancer_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class tratamientoenmuestra
    {
        public tratamientoenmuestra()
        {
            this.ensayoinvitro = new HashSet<ensayoinvitro>();
            this.ensayoinvitro1 = new HashSet<ensayoinvitro>();
            this.estacompuestade = new HashSet<estacompuestade>();
            this.tiene = new HashSet<tiene>();
        }
    
        public int idTratamientoEnMuestra { get; set; }
    
        public virtual ICollection<ensayoinvitro> ensayoinvitro { get; set; }
        public virtual ICollection<ensayoinvitro> ensayoinvitro1 { get; set; }
        public virtual ICollection<estacompuestade> estacompuestade { get; set; }
        public virtual ICollection<tiene> tiene { get; set; }
    }
}
